const configs = {
    de: {
        companionSpeciesData: {
        Hunde: {
            'Bornländer': { trickMod: '3', trainingMod: '2', trainingModules: ['Hütetier', 'Renntier', 'Tragetier', 'Wachtier', 'Zirkustier', 'Zugtier'] },
            Bosparaniel: { trickMod: '3', trainingMod: '0', trainingModules: ['Jagdtier', 'Suchtier', 'Zirkustier'] },
            'Bunter Hund': { trickMod: '2', trainingMod: '1', trainingModules: ['Tragetier', 'Wachtier', 'Zirkustier'] },
            'Espener Saupacker': { trickMod: '2', trainingMod: '1', trainingModules: ['Jagdtier', 'Wachtier'] },
            'Firnläufer': { trickMod: '2', trainingMod: '2', trainingModules: ['Renntier', 'Suchtier', 'Tragetier', 'Wachtier', 'Zugtier'] },
            'Garetisches Schlappohr': { trickMod: '3', trainingMod: '3', trainingModules: ['Jagdtier', 'Suchtier', 'Tragetier'] },
            'Mähnenwolf': { trickMod: '-2', trainingMod: '-2', trainingModules: ['Jagdtier', 'Kampftier', 'Wachtier'] },
            'Nivesischer Steppenhund': { trickMod: '2', trainingMod: '1', trainingModules: ['Hütetier', 'Jagdtier', 'Suchtier', 'Tragetier', 'Wachtier'] },
            'Onjaro-Bracke': { trickMod: '2', trainingMod: '2', trainingModules: ['Jagdtier', 'Kampftier', 'Suchtier', 'Wachtier'] },
            'Orkischer Kriegshund': { trickMod: '-1', trainingMod: '-1', trainingModules: ['Jagdtier', 'Kampftier', 'Wachtier', 'Tragetier', 'Zugtier'] },
            'Rahjatänzer': { trickMod: '3', trainingMod: '2', trainingModules: ['Zirkustier'] },
            'Schwarzer Olporter': { trickMod: '0', trainingMod: '2', trainingModules: ['Hütetier', 'Tragetier', 'Suchtier', 'Wachtier', 'Zirkustier', 'Zugtier'] },
            'Siebenwindläufer': { trickMod: '3', trainingMod: '2', trainingModules: ['Jagdtier', 'Renntier'] },
            'Therengar-Terrier': { trickMod: '1', trainingMod: '1', trainingModules: ['Jagdtier', 'Suchtier', 'Wachtier'] },
            Trollmops: { trickMod: '3', trainingMod: '-1', trainingModules: ['Zirkustier'] },
            Tuzaker: { trickMod: '2', trainingMod: '2', trainingModules: ['Jagdtier', 'Kampftier', 'Wachtier'] },
            'Wehrheimer Bluthund': { trickMod: '1', trainingMod: '1', trainingModules: ['Kampftier', 'Wachtier'] },
            'Weißer Koscher': { trickMod: '1', trainingMod: '1', trainingModules: ['Hütetier', 'Tragetier', 'Suchtier', 'Wachtier', 'Zirkustier', 'Zugtier'] },
            'Winhaller Wolfsjäger': { trickMod: '1', trainingMod: '2', trainingModules: ['Jagdtier', 'Wachtier'] },
            'Zornbrechter Bluthund': { trickMod: '-1', trainingMod: '-1', trainingModules: ['Kampftier', 'Wachtier', 'Zugtier'] },
        },
        Katzen: {
            'Al’Anfaner': { trickMod: '-1', trainingMod: '-2', trainingModules: ['Jagdtier', 'Kampftier', 'Zirkustier'] },
            Aranier: { trickMod: '-1', trainingMod: '-3', trainingModules: ['Kampftier', 'Renntier', 'Zirkustier'] },
            Burgenkatz: { trickMod: '0', trainingMod: '-1', trainingModules: ['Kampftier', 'Zirkustier'] },
            'Cha ay Zhamorrah': { trickMod: '-2', trainingMod: '-4', trainingModules: ['Kampftier', 'Zirkustier'] },
            Hexenkatz: { trickMod: '-1', trainingMod: '-3', trainingModules: ['Kampftier', 'Zirkustier'] },
            Nuala: { trickMod: '-2', trainingMod: '-4', trainingModules: ['Kampftier', 'Zirkustier'] },
            Scheunenkatz: { trickMod: '-1', trainingMod: '-3', trainingModules: ['Kampftier', 'Zirkustier'] },
            Wildkatze: { trickMod: '-3', trainingMod: '-4', trainingModules: ['Kampftier'] },
        },
        'Esel & Eselartige': {
            Esel: { trickMod: '0', trainingMod: '-1', trainingModules: ['Reittier', 'Tragetier', 'Zugtier'] },
            Grautier: { trickMod: '-1', trainingMod: '0', trainingModules: ['Reittier', 'Renntier', 'Tragetier', 'Zugtier'] },
            Maulesel: { trickMod: '0', trainingMod: '0', trainingModules: ['Reittier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Maultier: { trickMod: '0', trainingMod: '0', trainingModules: ['Reittier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
        },
        Pferde: {
            'Elenviner Vollblut': { trickMod: '-1', trainingMod: '1', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Goldfelser: { trickMod: '0', trainingMod: '-1', trainingModules: ['Kampftier', 'Reittier', 'Renntier'] },
            'Langmähne': { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            'Nordmähne': { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Shadif: { trickMod: '1', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier'] },
            'Svellttaler Kaltblut': { trickMod: '1', trainingMod: '1', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Teshkaler: { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier'] },
            'Tralloper Riese': { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Tulamide: { trickMod: '0', trainingMod: '-1', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier'] },
            Warunker: { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Yaquirtaler: { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zirkustier'] },
        },
        Ponys: {
            'Beilunker Zwergenpony': { trickMod: '0', trainingMod: '1', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
            Ferkinapony: { trickMod: '0', trainingMod: '-1', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
            Maraskanpony: { trickMod: '-1', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
            Orkpony: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
            Paavipony: { trickMod: '0', trainingMod: '0', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
        },
        Hoftiere: {
            Gans: { trickMod: '0', trainingMod: '-1', trainingModules: ['Wachtier', 'Zirkustier'] },
            Huhn: { trickMod: '1', trainingMod: '-1', trainingModules: ['Renntier', 'Zirkustier'] },
            Rind: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Tragetier', 'Zugtier'] },
            Schaf: { trickMod: '-1', trainingMod: '-2', trainingModules: ['Tragetier', 'Zugtier'] },
            Schwein: { trickMod: '0', trainingMod: '-2', trainingModules: ['Reittier', 'Suchtier', 'Tragetier', 'Zugtier', 'Zirkustier'] },
            Ziege: { trickMod: '-1', trainingMod: '-2', trainingModules: ['Tragetier', 'Zirkustier', 'Zugtier'] },
        },
        'Boten-, Jagd- und Ziervögel': {
            Adler: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Jagdtier', 'Kampftier'] },
            Falke: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Jagdtier', 'Kampftier'] },
            Papagei: { trickMod: '2', trainingMod: '-1', trainingModules: ['Zirkustier'] },
            Pfau: { trickMod: '0', trainingMod: '-1', trainingModules: ['Zirkustier'] },
            Rabe: { trickMod: '2', trainingMod: '1', trainingModules: ['Wachtier', 'Zirkustier'] },
            Singvogel: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Zirkustier'] },
            Taube: { trickMod: '0', trainingMod: '1', trainingModules: ['Tragetier', 'Zirkustier'] },
        },
        Wildtiere: {
            Affe: { trickMod: '2', trainingMod: '-2', trainingModules: ['Wachtier', 'Tragetier', 'Zirkustier'] },
            'Bär': { trickMod: '2', trainingMod: '-3', trainingModules: ['Zirkustier'] },
            Dachs: { trickMod: '-2', trainingMod: '-3', trainingModules: ['Suchtier', 'Tragetier', 'Zugtier'] },
            Eidechse: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Zirkustier'] },
            Elch: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
            Elefant: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Flugechse: { trickMod: '-3', trainingMod: '-4', trainingModules: ['Jagdtier', 'Reittier'] },
            Frettchen: { trickMod: '1', trainingMod: '-2', trainingModules: ['Zirkustier'] },
            Gelbschwanzskorpion: { trickMod: '-6', trainingMod: '*', trainingModules: [] },
            Greifkatze: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Zirkustier'] },
            Hippogriff: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Kampftier', 'Reittier'] },
            Hornechse: { trickMod: '-4', trainingMod: '-5', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zugtier'] },
            'Ikanaria-Schmetterling': { trickMod: '-7', trainingMod: '*', trainingModules: [] },
            Kamel: { trickMod: '-1', trainingMod: '1', trainingModules: ['Kampftier', 'Reittier', 'Renntier', 'Tragetier', 'Zugtier'] },
            Karen: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Tragetier', 'Zirkustier', 'Zugtier'] },
            Krokodil: { trickMod: '-3', trainingMod: '-5', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Mammut: { trickMod: '-2', trainingMod: '-3', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Zirkustier', 'Zugtier'] },
            Meckerdrache: { trickMod: '*', trainingMod: '*', trainingModules: [] },
            Mungo: { trickMod: '1', trainingMod: '-2', trainingModules: ['Zirkustier'] },
            Nachtwind: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Wachtier', 'Zirkustier'] },
            Pardel: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Renntier', 'Jagdtier', 'Kampftier', 'Wachtier', 'Zirkustier'] },
            Riesenalk: { trickMod: '-4', trainingMod: '-4', trainingModules: ['Jagdtier', 'Kampftier', 'Reittier', 'Tragetier', 'Wachtier'] },
            'Riesenhirschkäfer': { trickMod: '-4', trainingMod: '-5', trainingModules: ['Tragetier', 'Wachtier', 'Zugtier'] },
            'Schildkröte': { trickMod: '1', trainingMod: '1', trainingModules: ['Wachtier', 'Zirkustier'] },
            'Strauß': { trickMod: '-3', trainingMod: '-2', trainingModules: ['Reittier'] },
            Sumpfegel: { trickMod: '-7', trainingMod: '*', trainingModules: [] },
            Westwinddrache: { trickMod: '-7', trainingMod: '-7', trainingModules: ['Jagdtier', 'Kampftier', 'Reittier', 'Tragetier', 'Wachtier'] },
            Wildschwein: { trickMod: '-2', trainingMod: '-2', trainingModules: ['Kampftier', 'Reittier', 'Suchtier', 'Tragetier', 'Wachtier', 'Zugtier'] },
            Wolf: { trickMod: '-2', trainingMod: '-2', trainingModules: ['Jagdtier', 'Kampftier', 'Tragetier', 'Wachtier', 'Suchtier'] },
            Wollnashorn: { trickMod: '-3', trainingMod: '-4', trainingModules: ['Kampftier', 'Reittier', 'Tragetier', 'Wachtier', 'Zugtier'] },
        },
        },
        trainingTricks: {
        'Hütetier': ['Ablegen', 'Komm', 'Laut', 'Sitz', 'Treiben'],
        Jagdtier: ['Apport', 'Fass', 'Laut', 'Still', 'Such'],
        Kampftier: ['Aus', 'Fass', 'Fass 2'],
        Renntier: ['Komm', 'Sitz'],
        Wachtier: ['Ablegen', 'Komm', 'Laut', 'Sitz', 'Wache'],
        Zirkustier: ['Kunststück'],
        },
        trickRequirements: {
        Ablegen: { loyalty: 10, tricks: ['Komm', 'Sitz'] },
        Anzeigen: { loyalty: 6, tricks: ['Sitz'] },
        Apport: { loyalty: 8, tricks: [] },
        Aus: { loyalty: 8, tricks: ['Fass'] },
        Fass: { loyalty: 4, tricks: [] },
        'Fass 2': { loyalty: 8, tricks: ['Fass'] },
        'Fass 3': { loyalty: 10, tricks: ['Fass 2'] },
        Komm: { loyalty: 4, tricks: [] },
        'Kunststück': { loyalty: 4, tricks: ['Sitz'] },
        Laut: { loyalty: 6, tricks: [] },
        Platz: { loyalty: 8, tricks: ['Sitz'] },
        Sitz: { loyalty: 6, tricks: [] },
        Still: { loyalty: 8, tricks: [] },
        Such: { loyalty: 8, tricks: [] },
        Treiben: { loyalty: 10, tricks: [] },
        Wache: { loyalty: 10, tricks: [] },
        },
    },
    en: {
        companionSpeciesData: {
        Dogs: {
            'Bornland Dog': { trickMod: '3', trainingMod: '2', trainingModules: ['Herding Animal', 'Racing Animal', 'Pack Animal', 'Guard Animal', 'Circus Animal', 'Draft Animal'] },
            Bosparaniel: { trickMod: '3', trainingMod: '0', trainingModules: ['Hunting Animal', 'Search Animal', 'Circus Animal'] },
            'Colorful Dog': { trickMod: '2', trainingMod: '1', trainingModules: ['Pack Animal', 'Guard Animal', 'Circus Animal'] },
            'Espen Boarhound': { trickMod: '2', trainingMod: '1', trainingModules: ['Hunting Animal', 'Guard Animal'] },
            'Firn Runner': { trickMod: '2', trainingMod: '2', trainingModules: ['Racing Animal', 'Search Animal', 'Pack Animal', 'Guard Animal', 'Draft Animal'] },
            'Garetian Floppy-ear': { trickMod: '3', trainingMod: '3', trainingModules: ['Hunting Animal', 'Search Animal', 'Pack Animal'] },
            'Maned Wolf': { trickMod: '-2', trainingMod: '-2', trainingModules: ['Hunting Animal', 'Combat Animal', 'Guard Animal'] },
            'Nivese Steppe Dog': { trickMod: '2', trainingMod: '1', trainingModules: ['Herding Animal', 'Hunting Animal', 'Search Animal', 'Pack Animal', 'Guard Animal'] },
            'Onjaro Hound': { trickMod: '2', trainingMod: '2', trainingModules: ['Hunting Animal', 'Combat Animal', 'Search Animal', 'Guard Animal'] },
            'Orcish War Dog': { trickMod: '-1', trainingMod: '-1', trainingModules: ['Hunting Animal', 'Combat Animal', 'Guard Animal', 'Pack Animal', 'Draft Animal'] },
            'Rahja Dancer': { trickMod: '3', trainingMod: '2', trainingModules: ['Circus Animal'] },
            'Black Olport': { trickMod: '0', trainingMod: '2', trainingModules: ['Herding Animal', 'Pack Animal', 'Search Animal', 'Guard Animal', 'Circus Animal', 'Draft Animal'] },
            'Sevenwind Runner': { trickMod: '3', trainingMod: '2', trainingModules: ['Hunting Animal', 'Racing Animal'] },
            'Therengar Terrier': { trickMod: '1', trainingMod: '1', trainingModules: ['Hunting Animal', 'Search Animal', 'Guard Animal'] },
            'Troll Pug': { trickMod: '3', trainingMod: '-1', trainingModules: ['Circus Animal'] },
            Tuzaker: { trickMod: '2', trainingMod: '2', trainingModules: ['Hunting Animal', 'Combat Animal', 'Guard Animal'] },
            'Wehrheim Bloodhound': { trickMod: '1', trainingMod: '1', trainingModules: ['Combat Animal', 'Guard Animal'] },
            'White Kosch Dog': { trickMod: '1', trainingMod: '1', trainingModules: ['Herding Animal', 'Pack Animal', 'Search Animal', 'Guard Animal', 'Circus Animal', 'Draft Animal'] },
            'Winhall Wolfhound': { trickMod: '1', trainingMod: '2', trainingModules: ['Hunting Animal', 'Guard Animal'] },
            'Zornbrecht Bloodhound': { trickMod: '-1', trainingMod: '-1', trainingModules: ['Combat Animal', 'Guard Animal', 'Draft Animal'] },
        },
        Cats: {
            'Al’Anfan': { trickMod: '-1', trainingMod: '-2', trainingModules: ['Hunting Animal', 'Combat Animal', 'Circus Animal'] },
            Aranian: { trickMod: '-1', trainingMod: '-3', trainingModules: ['Combat Animal', 'Racing Animal', 'Circus Animal'] },
            'Castle Cat': { trickMod: '0', trainingMod: '-1', trainingModules: ['Combat Animal', 'Circus Animal'] },
            'Cha ay Zhamorrah': { trickMod: '-2', trainingMod: '-4', trainingModules: ['Combat Animal', 'Circus Animal'] },
            'Witch Cat': { trickMod: '-1', trainingMod: '-3', trainingModules: ['Combat Animal', 'Circus Animal'] },
            Nuala: { trickMod: '-2', trainingMod: '-4', trainingModules: ['Combat Animal', 'Circus Animal'] },
            'Barn Cat': { trickMod: '-1', trainingMod: '-3', trainingModules: ['Combat Animal', 'Circus Animal'] },
            'Wild Cat': { trickMod: '-3', trainingMod: '-4', trainingModules: ['Combat Animal'] },
        },
        'Donkeys & Mules': {
            Donkey: { trickMod: '0', trainingMod: '-1', trainingModules: ['Mount', 'Pack Animal', 'Draft Animal'] },
            'Gray Beast': { trickMod: '-1', trainingMod: '0', trainingModules: ['Mount', 'Racing Animal', 'Pack Animal', 'Draft Animal'] },
            Hinny: { trickMod: '0', trainingMod: '0', trainingModules: ['Mount', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Mule: { trickMod: '0', trainingMod: '0', trainingModules: ['Mount', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
        },
        Horses: {
            'Elenvina Thoroughbred': { trickMod: '-1', trainingMod: '1', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Goldfels: { trickMod: '0', trainingMod: '-1', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal'] },
            Longmane: { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Northmane: { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Shadif: { trickMod: '1', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal'] },
            'Svellttal Draft Horse': { trickMod: '1', trainingMod: '1', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Teshkal: { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal'] },
            'Trallop Giant': { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Tulamydian: { trickMod: '0', trainingMod: '-1', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal'] },
            Warunk: { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Yaquirtal: { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Circus Animal'] },
        },
        Ponies: {
            'Beilunk Dwarf Pony': { trickMod: '0', trainingMod: '1', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
            'Ferkina Pony': { trickMod: '0', trainingMod: '-1', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
            'Maraskan Pony': { trickMod: '-1', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
            'Orc Pony': { trickMod: '-1', trainingMod: '-1', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
            'Paavi Pony': { trickMod: '0', trainingMod: '0', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
        },
        'Farm Animals': {
            Goose: { trickMod: '0', trainingMod: '-1', trainingModules: ['Guard Animal', 'Circus Animal'] },
            Chicken: { trickMod: '1', trainingMod: '-1', trainingModules: ['Racing Animal', 'Circus Animal'] },
            'Cow/Bull': { trickMod: '-1', trainingMod: '-1', trainingModules: ['Pack Animal', 'Draft Animal'] },
            Sheep: { trickMod: '-1', trainingMod: '-2', trainingModules: ['Pack Animal', 'Draft Animal'] },
            Pig: { trickMod: '0', trainingMod: '-2', trainingModules: ['Mount', 'Search Animal', 'Pack Animal', 'Draft Animal', 'Circus Animal'] },
            Goat: { trickMod: '-1', trainingMod: '-2', trainingModules: ['Pack Animal', 'Circus Animal', 'Draft Animal'] },
        },
        'Messenger, Hunting and Pet Birds': {
            Eagle: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Hunting Animal', 'Combat Animal'] },
            Falcon: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Hunting Animal', 'Combat Animal'] },
            Parrot: { trickMod: '2', trainingMod: '-1', trainingModules: ['Circus Animal'] },
            Peacock: { trickMod: '0', trainingMod: '-1', trainingModules: ['Circus Animal'] },
            Raven: { trickMod: '2', trainingMod: '1', trainingModules: ['Guard Animal', 'Circus Animal'] },
            Songbird: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Circus Animal'] },
            Dove: { trickMod: '0', trainingMod: '1', trainingModules: ['Pack Animal', 'Circus Animal'] },
        },
        'Wild Animals': {
            Monkey: { trickMod: '2', trainingMod: '-2', trainingModules: ['Guard Animal', 'Pack Animal', 'Circus Animal'] },
            Bear: { trickMod: '2', trainingMod: '-3', trainingModules: ['Circus Animal'] },
            Badger: { trickMod: '-2', trainingMod: '-3', trainingModules: ['Search Animal', 'Pack Animal', 'Draft Animal'] },
            Lizard: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Circus Animal'] },
            Elk: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
            Elephant: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            'Flying Lizard': { trickMod: '-3', trainingMod: '-4', trainingModules: ['Hunting Animal', 'Mount'] },
            Ferret: { trickMod: '1', trainingMod: '-2', trainingModules: ['Circus Animal'] },
            'Yellow-tail Scorpion': { trickMod: '-6', trainingMod: '*', trainingModules: [] },
            'Griffin Cat': { trickMod: '-3', trainingMod: '-3', trainingModules: ['Circus Animal'] },
            Hippogriff: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Combat Animal', 'Mount'] },
            'Horned Lizard': { trickMod: '-4', trainingMod: '-5', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Draft Animal'] },
            'Ikanaria Butterfly': { trickMod: '-7', trainingMod: '*', trainingModules: [] },
            Camel: { trickMod: '-1', trainingMod: '1', trainingModules: ['Combat Animal', 'Mount', 'Racing Animal', 'Pack Animal', 'Draft Animal'] },
            Karen: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Crocodile: { trickMod: '-3', trainingMod: '-5', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            Mammoth: { trickMod: '-2', trainingMod: '-3', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Circus Animal', 'Draft Animal'] },
            'Grumble Dragon': { trickMod: '*', trainingMod: '*', trainingModules: [] },
            Mongoose: { trickMod: '1', trainingMod: '-2', trainingModules: ['Circus Animal'] },
            Nightwind: { trickMod: '-3', trainingMod: '-3', trainingModules: ['Guard Animal', 'Circus Animal'] },
            Pardel: { trickMod: '-1', trainingMod: '-1', trainingModules: ['Racing Animal', 'Hunting Animal', 'Combat Animal', 'Guard Animal', 'Circus Animal'] },
            'Giant Auk': { trickMod: '-4', trainingMod: '-4', trainingModules: ['Hunting Animal', 'Combat Animal', 'Mount', 'Pack Animal', 'Guard Animal'] },
            'Giant Stag Beetle': { trickMod: '-4', trainingMod: '-5', trainingModules: ['Pack Animal', 'Guard Animal', 'Draft Animal'] },
            Turtle: { trickMod: '1', trainingMod: '1', trainingModules: ['Guard Animal', 'Circus Animal'] },
            Ostrich: { trickMod: '-3', trainingMod: '-2', trainingModules: ['Mount'] },
            'Swamp Leech': { trickMod: '-7', trainingMod: '*', trainingModules: [] },
            'Westwind Dragon': { trickMod: '-7', trainingMod: '-7', trainingModules: ['Hunting Animal', 'Combat Animal', 'Mount', 'Pack Animal', 'Guard Animal'] },
            Boar: { trickMod: '-2', trainingMod: '-2', trainingModules: ['Combat Animal', 'Mount', 'Search Animal', 'Pack Animal', 'Guard Animal', 'Draft Animal'] },
            Wolf: { trickMod: '-2', trainingMod: '-2', trainingModules: ['Hunting Animal', 'Combat Animal', 'Pack Animal', 'Guard Animal', 'Search Animal'] },
            'Woolly Rhinoceros': { trickMod: '-3', trainingMod: '-4', trainingModules: ['Combat Animal', 'Mount', 'Pack Animal', 'Guard Animal', 'Draft Animal'] },
        },
        },
        trainingTricks: {
        'Herding Animal': ['Drop', 'Come', 'Speak', 'Sit', 'Herd'],
        'Hunting Animal': ['Fetch', 'Attack 1', 'Speak', 'Quiet', 'Search'],
        'Combat Animal': ['Drop it', 'Attack 1', 'Attack 2'],
        'Racing Animal': ['Come', 'Sit'],
        'Guard Animal': ['Drop', 'Come', 'Speak', 'Sit', 'Guard'],
        'Circus Animal': ['Trick'],
        },
        trickRequirements: {
        Drop: { loyalty: 10, tricks: ['Come', 'Sit'] },
        Point: { loyalty: 6, tricks: ['Sit'] },
        Fetch: { loyalty: 8, tricks: [] },
        'Drop it': { loyalty: 8, tricks: ['Attack 1'] },
        'Attack 1': { loyalty: 4, tricks: [] },
        'Attack 2': { loyalty: 8, tricks: ['Attack 1'] },
        'Attack 3': { loyalty: 10, tricks: ['Attack 2'] },
        Come: { loyalty: 4, tricks: [] },
        Trick: { loyalty: 4, tricks: ['Sit'] },
        Speak: { loyalty: 6, tricks: [] },
        Down: { loyalty: 8, tricks: ['Sit'] },
        Sit: { loyalty: 6, tricks: [] },
        Quiet: { loyalty: 8, tricks: [] },
        Search: { loyalty: 8, tricks: [] },
        Herd: { loyalty: 10, tricks: [] },
        Guard: { loyalty: 10, tricks: [] },
        },
    },
};

export default class CompanionConfig {
    static get companionSpeciesData() { return configs[game.i18n.lang === 'de' ? 'de' : 'en'].companionSpeciesData; }
    static get trainingTricks() { return configs[game.i18n.lang === 'de' ? 'de' : 'en'].trainingTricks; }
    static get trickRequirements() { return configs[game.i18n.lang === 'de' ? 'de' : 'en'].trickRequirements; }
}
