export const DSAKalender = {
  name: 'Der Zwölfgöttliche Kalender',
  description: 'Der allgemein verbreitete Kalender in Aventurien.',
  translationPrefix: 'CALENDAR.DSA',
  years: {
    yearSuffix: 'YearSuffix',
    yearZero: 0,
    firstWeekday: 3,
    leapYear: {
      leapStart: 1000000,
      leapInterval: 1000000,
    },
  },
  months: {
    values: [
      { name: 'July', abbreviation: 'JulyAbbr', ordinal: 1, days: 30 },
      { name: 'August', abbreviation: 'AugustAbbr', ordinal: 2, days: 30 },
      { name: 'September', abbreviation: 'SeptemberAbbr', ordinal: 3, days: 30 },
      { name: 'October', abbreviation: 'OctoberAbbr', ordinal: 4, days: 30 },
      { name: 'November', abbreviation: 'NovemberAbbr', ordinal: 5, days: 30 },
      { name: 'December', abbreviation: 'DecemberAbbr', ordinal: 6, days: 30 },
      { name: 'January', abbreviation: 'JanuaryAbbr', ordinal: 7, days: 30 },
      { name: 'February', abbreviation: 'FebruaryAbbr', ordinal: 8, days: 30 },
      { name: 'March', abbreviation: 'MarchAbbr', ordinal: 9, days: 30 },
      { name: 'April', abbreviation: 'AprilAbbr', ordinal: 10, days: 30 },
      { name: 'May', abbreviation: 'MayAbbr', ordinal: 11, days: 30 },
      { name: 'June', abbreviation: 'JuneAbbr', ordinal: 12, days: 30 },
      { name: 'NamenloseTage', abbreviation: 'NamenloseTageAbbr', ordinal: 13, days: 5 }
    ],
  },
  days: {
    values: [
      { name: 'Monday', abbreviation: 'MondayAbbr', ordinal: 1 },
      { name: 'Tuesday', abbreviation: 'TuesdayAbbr', ordinal: 2 },
      { name: 'Wednesday', abbreviation: 'WednesdayAbbr', ordinal: 3 },
      { name: 'Thursday', abbreviation: 'ThursdayAbbr', ordinal: 4, isRestDay: true },
      { name: 'Friday', abbreviation: 'FridayAbbr', ordinal: 5 },
      { name: 'Saturday', abbreviation: 'SaturdayAbbr', ordinal: 6 },
      { name: 'Sunday', abbreviation: 'SundayAbbr', ordinal: 7 }
    ],
    daysPerYear: 365,
    hoursPerDay: 24,
    minutesPerHour: 60,
    secondsPerMinute: 60,
  },
  seasons: {
    values: [
      { name: 'Summer', monthStart: 0, dayStart: 0 },
      { name: 'Fall', monthStart: 2, dayStart: 21 },
      { name: 'Winter', monthStart: 5, dayStart: 20 },
      { name: 'Spring', monthStart: 8, dayStart: 19 },
      { name: 'Summer', monthStart: 11, dayStart: 20 },
      { name: 'NamenloseTage', monthStart: 12, dayStart: 0 }
    ],
  },
  moon: {
    values: [
      { name: 'ToteMada', dayStart: 0, lightAdjust: 0 },
      { name: 'AuffuellenderKelch', dayStart: 1, lightAdjust: 0.25 },
      { name: 'Kelch', dayStart: 7, lightAdjust: 0.5 },
      { name: 'ZunehmendesRad', dayStart: 8, lightAdjust: 0.75 },
      { name: 'Rad', dayStart: 14, lightAdjust: 1 },
      { name: 'AbnehmendesRad', dayStart: 15, lightAdjust: 0.75 },
      { name: 'Helm', dayStart: 21, lightAdjust: 0.5 },
      { name: 'AbnehmenderHelm', dayStart: 22, lightAdjust: 0.25 },
    ]
  },
  holidays: {
    values: [
      { name: 'Sommersonnenwende', month: 0, dayStart: 0, gods: ['Praios', 'Phex', 'Nandus', 'Sumu', 'Rikai'] },
      { name: 'Greifenfest', month: 0, dayStart: 1, dayEnd: 2 },
      { name: 'Tag des Schwurs', month: 1, dayStart: 4, gods: ['Rondra'] },
      { name: 'Schwertfest', month: 1, dayStart: 14, dayEnd: 15, gods: ['Rondra', 'Kor'] },
      { name: 'Tag des Wassers', month: 2, dayStart: 0, gods: ['Efferd', 'Swafnir'] },
      { name: 'Nebelfest', month: 2, dayStart: 15, gods: ['Efferd'] },
      { name: 'Tag des Kampfes', month: 2, dayStart: 21, gods: ['Brazoragh'] },
      { name: 'Fischerfest', month: 2, dayStart: 29, gods: ['Efferd'] },
      { name: 'Prüfungsfest', month: 2, dayStart: 29, gods: ['Hesinde'] },
      { name: 'Tag der Heimkehr', month: 3, dayStart: 0, gods: ['Travia'] },
      { name: 'Feste des Ausgleichs', month: 3, dayStart: 0, gods: ['Phex'] },
      { name: 'Fest der eingebrachten Früchte', month: 3, dayStart: 0, dayEnd: 2, gods: ['Peraine', 'Travia'] },
      { name: 'Tag der Helden', month: 3, dayStart: 3, gods: ['Rondra'] },
      { name: 'Tag der Treue', month: 3, dayStart: 11, gods: ['Travia'] },
      { name: 'Tag des Heiligen Gilborn', month: 3, dayStart: 28, gods: ['Praios'] },
      { name: 'Totenfest', month: 4, dayStart: 0, gods: ['Boron', 'Marbo', 'Tairach'] },
      { name: 'Allaventurisches Gauklertreffen', month: 4, dayStart: 1, dayEnd: 7, location: 'Khunchom' },
      { name: 'Tag der Besinnung', month: 4, dayStart: 21, gods: ['Marbo'] },
      { name: 'Tag des Großen Schlafs', month: 4, dayStart: 29, gods: ['Boron'] },
      { name: 'Rohals Verhüllung', month: 5, dayStart: 7 },
      { name: 'Opernsaison in Vinsalt', month: 5, dayStart: 19, location: 'Vinsalt' },
      { name: 'Erleuchtungsfest', month: 5, dayStart: 29, gods: ['Hesinde'] },
      { name: 'Wintersonnenwende', month: 6, dayStart: 0, gods: ['Firun', 'Phex', 'Nandus', 'Sumu', 'Rikai'] },
      { name: 'Tag des Hirsches', month: 6, dayStart: 11, gods: ['Firun'], location: 'Bjaldorn' },
      { name: 'Tag der Ifirn', month: 6, dayStart: 29, gods: ['Firun', 'Ifirn'] },
      { name: 'Tag der Erneuerung', month: 7, dayStart: 29, gods: ['Tsa'] },
      { name: 'Tag des Phex', month: 8, dayStart: 15, gods: ['Phex'] },
      { name: 'Glückstag', month: 8, dayStart: 23, gods: ['Phex', 'Aves'] },
      { name: 'Versenkungsfest', month: 8, dayStart: 29, gods: ['Hesinde'] },
      { name: 'Tag der Saat', month: 9, dayStart: 0, gods: ['Peraine'] },
      { name: 'Feste des Ausgleichs', month: 9, dayStart: 0, gods: ['Phex'] },
      { name: 'Thalionmeltag', month: 9, dayStart: 3, gods: ['Rondra'] },
      { name: 'Wiederkehr der Hornisse', month: 9, dayStart: 7, gods: ['Shinxir'] },
      { name: 'Bardentreffen', month: 9, dayStart: 6, dayEnd: 11 },
      { name: 'Tag des Feuers', month: 10, dayStart: 0, gods: ['Angrosch', 'Gravesh'] },
      { name: 'Tag des Aufbruchs', month: 10, dayStart: 7, gods: ['Angrosch'] },
      { name: 'Tag der Waffenschmiede', month: 10, dayStart: 20, gods: ['Ingerimm'] },
      { name: 'Tag der Dritten Dämonenschlacht', month: 10, dayStart: 22 },
      { name: 'Fest der Freuden', month: 11, dayStart: 0, dayEnd: 6, gods: ['Rahja'] },
      { name: 'Reinigungsfest', month: 11, dayStart: 29, gods: ['Hesinde', 'Levthan'] },
      { name: 'Tage des Namenlosen', month: 12, dayStart: 0, dayEnd: 4, gods: ['Namenloser'] },
    ]
  }
};
